### ISSUE TITLE
Coud you please tag releases

### ISSUE THREAD

**Issue by ppd** [raulroda/qet_tb_generator-plugin#2]
Hi,

I see you expressing releases via the commit messages. I have one request: Could you also tag those commits? E.g. 2f4e84adfa439eda6a86aea3438746e289e2b135 would be tagged `1.3.0`.

This would be quite handy for pinning to a specific version in the QElectroTech snaps or flatpaks. Thank you.

**Comment by ppd** [comment]
ping @raulroda :)

**Comment by raulroda** [comment]
Done. Thanks for the advice.
